//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CabBooking()
        {
            this.BookedBies = new HashSet<BookedBy>();
        }
    
        public int BookingId { get; set; }
        public int PaymentId { get; set; }
        public System.DateTime Date { get; set; }
        public string BeginigLocation { get; set; }
        public string EndLocation { get; set; }
        public int TouristId { get; set; }
        public int CabId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedBy> BookedBies { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Tourist Tourist { get; set; }
    }
}
