//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatWhoToWhom
    {
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public int ChatId { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual TourGuide TourGuide { get; set; }
        public virtual TourGuide TourGuide1 { get; set; }
        public virtual Tourist Tourist { get; set; }
        public virtual Tourist Tourist1 { get; set; }
    }
}
