//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRating
    {
        public int TouristId { get; set; }
        public int HotelId { get; set; }
        public int RatingValue { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Tourist Tourist { get; set; }
    }
}
