//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thanujaEntities : DbContext
    {
        public thanujaEntities()
            : base("name=thanujaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookedBy> BookedBies { get; set; }
        public virtual DbSet<CabBooking> CabBookings { get; set; }
        public virtual DbSet<CabDetail> CabDetails { get; set; }
        public virtual DbSet<CabRating> CabRatings { get; set; }
        public virtual DbSet<CabService> CabServices { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<ChatGroup> ChatGroups { get; set; }
        public virtual DbSet<ChatGrouping> ChatGroupings { get; set; }
        public virtual DbSet<ChatMember> ChatMembers { get; set; }
        public virtual DbSet<ChatWhoToWhom> ChatWhoToWhoms { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelRating> HotelRatings { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomBooking> RoomBookings { get; set; }
        public virtual DbSet<RoomDetail> RoomDetails { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<TourGuide> TourGuides { get; set; }
        public virtual DbSet<TourGuideBooking> TourGuideBookings { get; set; }
        public virtual DbSet<TourGuideRating> TourGuideRatings { get; set; }
        public virtual DbSet<Tourist> Tourists { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
    }
}
