//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomId { get; set; }
        public int HotelId { get; set; }
        public bool RoomStatus { get; set; }
        public int FloorNo { get; set; }
        public int ReservationId { get; set; }
        public int BookingId { get; set; }
        public int RoomTypeId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual RoomBooking RoomBooking { get; set; }
    }
}
