//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomBooking()
        {
            this.BookedBies = new HashSet<BookedBy>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int BookingId { get; set; }
        public int RoomId { get; set; }
        public int PaymentId { get; set; }
        public System.DateTime Date { get; set; }
        public int NoOfRooms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedBy> BookedBies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual RoomBooking RoomBooking1 { get; set; }
        public virtual RoomBooking RoomBooking2 { get; set; }
    }
}
