//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDetail
    {
        public int HotelId { get; set; }
        public int RoomTypeId { get; set; }
        public int Availability { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual RoomDetail RoomDetails1 { get; set; }
        public virtual RoomDetail RoomDetail1 { get; set; }
    }
}
