//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGuide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourGuide()
        {
            this.ChatWhoToWhoms = new HashSet<ChatWhoToWhom>();
            this.ChatWhoToWhoms1 = new HashSet<ChatWhoToWhom>();
        }
    
        public int GuideId { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public bool ChatStatus { get; set; }
        public int Rank { get; set; }
        public int ChargePerDay { get; set; }
        public int BookingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatWhoToWhom> ChatWhoToWhoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatWhoToWhom> ChatWhoToWhoms1 { get; set; }
        public virtual TourGuide TourGuide1 { get; set; }
        public virtual TourGuide TourGuide2 { get; set; }
    }
}
